import Head from "next/head";
import React from "react";

export const MetaTags = ({ children }: React.PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Shitty Polls</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};
